title: "Daily Notes"
description: "张琳琳团队笔记汇总"
theme: minima

collections:
  notes:
    output: true
    permalink: /notes/:name/

markdown: kramdown
highlighter: rouge
rouge:
  theme: github
kramdown:
  input: GFM
  auto_ids: true
  toc_levels: 2..3
