title: "Daily Notes"
description: "团队每日笔记系统 - Powered by GitHub Pages"
theme: minima
author: "DailyNotes-Team"
timezone: Asia/Shanghai

# Jekyll 设置
markdown: kramdown
paginate: 10
paginate_path: "/page:num/"
