title: "Daily Notes"
description: "张琳琳团队笔记汇总  tengwen2018.github.io liqian.github.io liuxinzhi.github.io lijie.github.io chenyaru.github.io lichenrui.github.io pengzhangjie.github.io"
theme: minima

collections:
  notes:
    output: true
    permalink: /notes/:name/

markdown: kramdown
highlighter: rouge
rouge:
  theme: github
kramdown:
  input: GFM
  auto_ids: true
  toc_levels: 2..3
