title: "Daily Notes"
description: "张琳琳团队每月笔记汇总"
theme: minima

collections:
  notes:
    output: true
    permalink: /notes/:name/

markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  toc_levels: 2..3
