title: "Daily Notes"
description: "张琳琳团队每月笔记汇总"
theme: minima

collections:
  notes:
    output: true
    permalink: /notes/:name/

## 显示代码行号
```yaml
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true

markdown: kramdown
highlighter: rouge
rouge:
  theme: github
